<a href="https://colab.research.google.com/github/xiantail/py4fi2nd/blob/master/06_object_orientation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="http://hilpisch.com/tpq_logo.png" alt="The Python Quants" width="35%" align="right" border="0"><br>

# Python for Finance (2nd ed.)

**Mastering Data-Driven Finance**

&copy; Dr. Yves J. Hilpisch | The Python Quants GmbH

<img src="http://hilpisch.com/images/py4fi_2nd_shadow.png" width="300px" align="left">

# Object Oriented Programming

## Introduction

In [0]:
class HumanBeing(object):  
    def __init__(self, first_name, eye_color):  
        self.first_name = first_name  
        self.eye_color = eye_color  
        self.position = 0  
    def walk_steps(self, steps):  
        self.position += steps  

In [0]:
Sandra = HumanBeing('Sandra', 'blue')  

In [0]:
Sandra.first_name  

'Sandra'

In [0]:
Sandra.position  

0

In [0]:
Sandra.walk_steps(5)  

In [0]:
Sandra.position  

5

## A Brief Look at Standard Objects

### int

In [0]:
n = 5  

In [0]:
type(n)  

int

In [0]:
n.numerator  

5

In [0]:
n.bit_length()  

3

In [0]:
n + n  

10

In [0]:
2 * n  

10

In [0]:
n.__sizeof__()  

28

### list

In [0]:
l = [1, 2, 3, 4]  

In [0]:
type(l)  

list

In [0]:
l[0]  

1

In [0]:
l.append(10)  

In [0]:
l + l  

[1, 2, 3, 4, 10, 1, 2, 3, 4, 10]

In [0]:
2 * l  

[1, 2, 3, 4, 10, 1, 2, 3, 4, 10]

In [0]:
sum(l)  

20

In [0]:
l.__sizeof__()  

104

### ndarray

In [0]:
import numpy as np  

In [0]:
a = np.arange(16).reshape((4, 4))  

In [0]:
a  

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [0]:
type(a)  

numpy.ndarray

In [0]:
a.nbytes  

128

In [0]:
a.sum()  

120

In [0]:
a.cumsum(axis=0)  

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21],
       [24, 28, 32, 36]])

In [0]:
a + a  

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [0]:
2 * a  

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [0]:
sum(a)  

array([24, 28, 32, 36])

In [0]:
np.sum(a)  

120

In [0]:
a.__sizeof__()  

112

### DataFrame

In [0]:
import pandas as pd  

In [0]:
df = pd.DataFrame(a, columns=list('abcd'))  

In [0]:
type(df)  

pandas.core.frame.DataFrame

In [0]:
df.columns  

Index(['a', 'b', 'c', 'd'], dtype='object')

In [0]:
df.sum()  

a    24
b    28
c    32
d    36
dtype: int64

In [0]:
df.cumsum()  

a   b   c   d
0   0   1   2   3
1   4   6   8  10
2  12  15  18  21
3  24  28  32  36

In [0]:
df + df  

a   b   c   d
0   0   2   4   6
1   8  10  12  14
2  16  18  20  22
3  24  26  28  30

In [0]:
2 * df  

a   b   c   d
0   0   2   4   6
1   8  10  12  14
2  16  18  20  22
3  24  26  28  30

In [0]:
np.sum(df)  

a    24
b    28
c    32
d    36
dtype: int64

In [0]:
df.__sizeof__()  

256

## Basics of Python Classes

In [0]:
class FinancialInstrument(object):  
    pass  

In [0]:
fi = FinancialInstrument()  

In [0]:
type(fi)  

__main__.FinancialInstrument

In [0]:
fi  

In [0]:
fi.__str__()  

'<__main__.FinancialInstrument object at 0x7facf218a208>'

In [0]:
fi.price = 100  

In [0]:
fi.price  

100

In [0]:
class FinancialInstrument(object):
    author = 'Yves Hilpisch'  
    def __init__(self, symbol, price):  
        self.symbol = symbol  
        self.price = price  

In [0]:
FinancialInstrument.author  

'Yves Hilpisch'

In [0]:
aapl = FinancialInstrument('AAPL', 100)  

In [0]:
aapl.symbol  

'AAPL'

In [0]:
aapl.author  

'Yves Hilpisch'

In [0]:
aapl.price = 105  

In [0]:
aapl.price  

105

In [0]:
class FinancialInstrument(FinancialInstrument):  
    def get_price(self):  
        return self.price  
    def set_price(self, price):  
        self.price = price  

In [0]:
fi = FinancialInstrument('AAPL', 100)  

In [0]:
fi.get_price()  

100

In [0]:
fi.set_price(105)  

In [0]:
fi.get_price()  

105

In [0]:
fi.price  

105

In [0]:
class FinancialInstrument(object):
    def __init__(self, symbol, price):
        self.symbol = symbol  
        self.__price = price  
    def get_price(self):
        return self.__price
    def set_price(self, price):
        self.__price = price

In [0]:
fi = FinancialInstrument('AAPL', 100)

In [0]:
fi.get_price()  

100

In [0]:
# causes intentional error
# fi.__price  

In [0]:
fi._FinancialInstrument__price  

100

In [0]:
fi._FinancialInstrument__price = 105  

In [0]:
fi.set_price(100)  

In [0]:
class PortfolioPosition(object):
    def __init__(self, financial_instrument, position_size):
        self.position = financial_instrument  
        self.__position_size = position_size  
    def get_position_size(self):
        return self.__position_size
    def update_position_size(self, position_size):
        self.__position_size = position_size
    def get_position_value(self):
        return self.__position_size * \
               self.position.get_price()  

In [0]:
pp = PortfolioPosition(fi, 10)

In [0]:
pp.get_position_size()

10

In [0]:
pp.get_position_value()  

1000

In [0]:
pp.position.get_price()  

100

In [0]:
pp.position.set_price(105)  

In [0]:
pp.get_position_value()  

1050

## Python Data Model

In [0]:
class Vector(object):
    def __init__(self, x=0, y=0, z=0):  
        self.x = x  
        self.y = y  
        self.z = z  

In [0]:
v = Vector(1, 2, 3)  

In [0]:
v  

In [0]:
class Vector(Vector):
    def __repr__(self):
        return 'Vector(%r, %r, %r)' % (self.x, self.y, self.z)

In [0]:
v = Vector(1, 2, 3)

In [0]:
v  

Vector(1, 2, 3)

In [0]:
print(v)  

Vector(1, 2, 3)


In [0]:
class Vector(Vector):
    def __abs__(self):
        return (self.x ** 2 +  self.y ** 2 +
                self.z ** 2) ** 0.5  
    
    def __bool__(self):
        return bool(abs(self))

In [0]:
v = Vector(1, 2, -1)  

In [0]:
abs(v)

2.449489742783178

In [0]:
bool(v)

True

In [0]:
v = Vector()  

In [0]:
v  

Vector(0, 0, 0)

In [0]:
abs(v)

0.0

In [0]:
bool(v)

False

In [0]:
class Vector(Vector):
    def __add__(self, other):
        x = self.x + other.x
        y = self.y + other.y
        z = self.z + other.z
        return Vector(x, y, z)  
    
    def __mul__(self, scalar):
        return Vector(self.x * scalar,
                      self.y * scalar,
                      self.z * scalar)  

In [0]:
v = Vector(1, 2, 3)

In [0]:
v + Vector(2, 3, 4)

Vector(3, 5, 7)

In [0]:
v * 2

Vector(2, 4, 6)

In [0]:
class Vector(Vector):
    def __len__(self):
        return 3  
    
    def __getitem__(self, i):
        if i in [0, -3]: return self.x
        elif i in [1, -2]: return self.y
        elif i in [2, -1]: return self.z
        else: raise IndexError('Index out of range.')

In [0]:
v = Vector(1, 2, 3)

In [0]:
len(v)

3

In [0]:
v[0]

1

In [0]:
v[-2]

2

In [0]:
# causes intentional error
# v[3]

In [0]:
class Vector(Vector):
    def __iter__(self):
        for i in range(len(self)):
            yield self[i]

In [0]:
v = Vector(1, 2, 3)

In [0]:
for i in range(3):  
    print(v[i])  

1
2
3


In [0]:
for coordinate in v:  
    print(coordinate)  

1
2
3


In [0]:
class Vector(object):
    def __init__(self, x=0, y=0, z=0):
        self.x = x
        self.y = y
        self.z = z
    
    def __repr__(self):
        return 'Vector(%r, %r, %r)' % (self.x, self.y, self.z)
    
    def __abs__(self):
        return (self.x ** 2 +  self.y ** 2 + self.z ** 2) ** 0.5
    
    def __bool__(self):
        return bool(abs(self))
    
    def __add__(self, other):
        x = self.x + other.x
        y = self.y + other.y
        z = self.z + other.z
        return Vector(x, y, z)
    
    def __mul__(self, scalar):
        return Vector(self.x * scalar,
                      self.y * scalar,
                      self.z * scalar)
    
    def __len__(self):
        return 3
    
    def __getitem__(self, i):
        if i in [0, -3]: return self.x
        elif i in [1, -2]: return self.y
        elif i in [2, -1]: return self.z
        else: raise IndexError('Index out of range.')
            
    def __iter__(self):
        for i in range(len(self)):
            yield self[i]

<img src="http://hilpisch.com/tpq_logo.png" alt="The Python Quants" width="35%" align="right" border="0"><br>

<a href="http://tpq.io" target="_blank">http://tpq.io</a> | <a href="http://twitter.com/dyjh" target="_blank">@dyjh</a> | <a href="mailto:training@tpq.io">training@tpq.io</a>